#!/usr/bin/env python3

a = int(input())
t = ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
a = int(input())
t = t + ((a % 2) * a)
print(t)
